### ISSUE TITLE
Implement get_user_model same as get_group_model

### ISSUE THREAD

**Issue by omidraha** [15five/django-scim2#100]
**Is your feature request related to a problem? Please describe.**

Currently for detect user model, the `django-scim2` use `get_user_model`  from the `Django` builtin function, 
And `get_user_model` of  `Django`, use  `settings.AUTH_USER_MODEL`

```python
    user = get_user_model().objects.get(id=1)
    scim_user = SCIMUser(user)
```
But if you want to use another defined model for user of scim that is related to the customized user model of  `settings.AUTH_USER_MODEL` , there is no settings for doing that. we should override all related  files as `urls`, `views`, `filter` and `adapter`.

**Describe the solution you'd like**

Same as `get_user_model` that get group model from the `scim_settings` settings:

```python
def get_group_model():
    """
    Return the group model.
    """
    return scim_settings.GROUP_MODEL
```

```python
SCIM_SERVICE_PROVIDER = {
      'GROUP_MODEL': 'accounts.models.Group',
}
```
Implement it as:

```python
def get_user_model():
    """
    Return the user model.
    """
    return scim_settings.USER_MODEL
```

```python
SCIM_SERVICE_PROVIDER = {
      'USER_MODEL': 'accounts.models.UserSCIM',
}
```

**Describe alternatives you've considered**

Override `model_cls_getter`  of `UsersView` and `UserFilterQuery, and `SCIMUser.handle_add `

**Additional context**
-

**Comment by logston** [comment]
This is an easy fix, so I've pushed up a small change.

**Comment by omidraha** [comment]
Yes, of course.
Thanks.

**Comment by omidraha** [comment]
I  installed it by:

```pip install git+https://github.com/15five/django-scim2.git@bf4f58fbbe7ff0c7752cb79175eada6a8edacdcf```

And everything is right.

‌But just as a note  based on this part of the code:

```python
return scim_settings.USER_MODEL_GETTER()
```
That is compatible with this part of code:
```python
    'USER_MODEL_GETTER': 'django.contrib.auth.get_user_model',
```

Now in the `SCIM_SERVICE_PROVIDER` we can't directly refer to the model class like this:

```python
SCIM_SERVICE_PROVIDER = {
    'USER_MODEL_GETTER': 'accounts.models.UserSCIM',
    'GROUP_MODEL': 'accounts.models.GroupSCIM',
}
```
This only works for `GROUP_MODEL` but doesn't work with `USER_MODEL_GETTER`.

So we should define a extra method like this:
```python
def get_user_scim_model():
    return UserSCIM
```

And use this function as:
```python
SCIM_SERVICE_PROVIDER = {
    'USER_MODEL_GETTER': 'scim.models.get_user_scim_model',
    'GROUP_MODEL': 'accounts.models.Group',
```

Because the settings are distinguished by this `_GETTER` prefix.
It may be possible to remove this `_GETTER`  prefix and  this distinction by checking its callable.

**Comment by logston** [comment]
Hi @omidraha, if I understand correctly, you'd like to be able to reference the model directly? Rather than reference a function that returns the model? If so, I think I disagree for this project. The reason being that the typical way of getting access to the default Django model is via a function call `get_user_model`. I'd like to provide that same interface in this project. If users wish to return a custom model, they can do so by writing there own small `get_custom_user_model` function and returning their model of choice.

**Comment by omidraha** [comment]
You right, Can you merge it into the master branch?

**Comment by logston** [comment]
Yep, soon as I get an LGTM from my reviewers.

**Comment by omidraha** [comment]
And in [PyPI](https://pypi.org/project/django-scim2/)?

**Comment by logston** [comment]
Yep, I just need https://github.com/15five/django-scim2/pull/102 reviewed and merged and I get release a new version to pypi.
