### ISSUE TITLE
asking for username and password when accessing v2/scim/Users

### ISSUE THREAD

**Issue by devendra-rgb** [15five/django-scim2#112]
I don't know why it is asking for user credentials v2/scim/Users how to get credentials I am giving my admin credentials it is saying unauthorized

**Comment by logston** [comment]
Hi @devendra-rgb, did you set up an [authentication backend](https://github.com/15five/django-scim2/blob/master/demo/root/settings.py#L57-L62) and send appropriate headers? 

Note that django-scim2 does [very little in terms of authentication](https://github.com/15five/django-scim2/blob/master/src/django_scim/middleware.py#L52) and the issue you describe sounds like an authentication issue outside of this app.
