### ISSUE TITLE
Unable to Decouple the User Model 

### ISSUE THREAD

**Issue by devendra-rgb** [15five/django-scim2#115]
I have requirements such that I am not allowed to do any migrations to my default user model, so I extended my user model to a new SCIM_USER_MODEL by considering User model with one to one relation. now in settings file when I am mentioning the USER_MODEL_GETTER it is saying "Manager isn't accessible via SCIM_USER_MODEL instances". Please help me on this

**Comment by logston** [comment]
Hi @devendra-rgb, it sounds like the your SCIM user model may not inherit from the `AbstractSCIMUserMixin`. https://github.com/15five/django-scim2/blob/67bac7db5c6229a63b692c83cb96a0aa30eec2f2/src/django_scim/models.py#L159C7-L159C28

Or perhaps this is your issue: https://stackoverflow.com/a/3874563/1927634

Unfortunately, if that's not the issue, I'm not sure I'd be able to give you more direction. There's very little bandwidth on this project for general usage help.

**Comment by logston** [comment]
Sorry @devendra-rgb, I can't arrange that. Right now, I'm quite overloaded and, further, I'm not sure I would be to support these types of requests going forward. Thus I don't want to set a precedent I can't maintain. If you have concrete and well detailed questions, you can always open them here.

**Comment by devendra-rgb** [comment]
Hi @logston  my problem solved thanks for supporting 💯  : )
