### ISSUE TITLE
externalId is not stored when creating a user and not returned when retrieving a user

### ISSUE THREAD

**Issue by erfaan** [15five/django-scim2#21]
**Describe the bug**
externalId is not stored in User when creating a new user via POST method and not returned when retrieving a user via GET.

**To Reproduce**
`curl -H "Authorization: Bearer xxxxx" "http://localhost:8000/scim/v2/Users" -d '{"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"externalId":"0a21f0f2-8d2a-4f8e-bf98-7363c4aed4ef","userName":"Test_User_ab6490ee-1e48-479e-a20b-2d77186b5dd1","active":true,"emails":[{"primary":true,"type":"work","value":"Test_User_fd0ea19b-0777-472c-9f96-4f70d2226f2e@testuser.com"}],"meta":{"resourceType":"User"},"name":{"formatted":"givenName familyName","familyName":"familyName","givenName":"givenName"},"roles":[]}' -X POST`

`curl -H "Authorization: Bearer xxxxxx" "http://localhost:8000/scim/v2/Users/14"`

**Expected behavior**
externalId should be stored in model and returned when retrieving a user.

**Comment by logston** [comment]
Good point. This should be happening. Will create a test case and patch when I get the chance.
