### ISSUE TITLE
PATCH request to update the user fails

### ISSUE THREAD

**Issue by erfaan** [15five/django-scim2#22]
**Describe the bug**
PATCH request to update user attributes results in 500 error.

**To Reproduce**
`curl -H "Authorization: Bearer xxxxxx" "http://localhost:8000/scim/v2/Users/14" -d '{"schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations": [{"op": "Replace","path": "name.familyName","value": "updatedFamilyName"}]}' -X PATCH`

**Expected behavior**
User's attribute should be updated and user should be returned.

**Stacktrace**
```
Traceback (most recent call last):
  File "/xxxxxxxxxx/django_scim/views.py", line 91, in dispatch
    return super(SCIMView, self).dispatch(request, *args, **kwargs)
  File "/xxxxxxxxxx/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/xxxxxxxxxx/django_scim/views.py", line 336, in patch
    scim_obj.handle_operations(operations)
  File "/xxxxxxxxxx/django_scim/adapters.py", line 87, in handle_operations
    handler(path, value, operation)
  File "/xxxxxxxxxx/django_scim/adapters.py", line 270, in handle_replace
    for attr, attr_value in attrs.items():
AttributeError: 'unicode' object has no attribute 'items'

```

**Comment by logston** [comment]
Thank you for this! It might be a while before I can tackle it as this is a part-time project at my current job. It is on my radar though.

**Comment by omidraha** [comment]
I got similar error, for this incoming parameters:

```python
            path: [
                 [
                     "userName",
                     null,
                     null
                 ]
             ],
            value:mail@example.com,
            operation: {'op': 'Replace', 'path': 'userName', 'value': 'mail@example.com'}
```

**Comment by logston** [comment]
Hmm, if you are having an issue, can you open a new ticket and post as much context as you have? 

Eg. stack trace, input, SCIM URL, etc.
