### ISSUE TITLE
Document how to create custom schemas

### ISSUE THREAD

**Issue by stefanfoulis** [15five/django-scim2#33]
Add documentation on how a custom schema for custom object types can be integrated (can they?) with django-scim2.

**Comment by stefanfoulis** [comment]
I am happy to help. I am currently trying to figure out if/how this can work by looking through the code. Any pointers would be very welcome.

**Comment by logston** [comment]
Sorry for the delay! And thank you for your interest. 

Yes you can customize this. 


Override this setting:

https://github.com/15five/django-scim2/blob/5edae54af402862b43fce8271c32c4d8eb5950b8/src/django_scim/settings.py#L35

And have a function like the following return your custom schemas:

https://github.com/15five/django-scim2/blob/5aed87d6ebe1a997478e0a6778913e712b8d97c7/src/django_scim/schemas/__init__.py#L25

Thanks again @stefanfoulis and any added documentation would be welcome.
