### ISSUE TITLE
ATTR_MAP hard-linked to UserFilterQuery ignoring USER_FILTER_PARSER setting

### ISSUE THREAD

**Issue by horida** [15five/django-scim2#38]
**Describe the bug**
In the [adapter](https://github.com/15five/django-scim2/blob/master/src/django_scim/adapters.py#L299) the ATTR_MAP is set to the attr_map of the UserFilterQuery objects:
```python
ATTR_MAP = filters.UserFilterQuery.attr_map
```

There is however a [setting](https://github.com/15five/django-scim2/blob/master/src/django_scim/settings.py#L29) where the UserFilterQuery object can be overwritten by a custom object.

**Expected behavior**
The object specified in the `USER_FILTER_PARSER` setting should be used. This can be achieved by using `utils.get_user_filter_parser` (see [here](https://github.com/15five/django-scim2/blob/master/src/django_scim/utils.py#L28)).

**Comment by horida** [comment]
Hi @logston , it looks like you're the (most) active contributor recently. Could you have a look at this one?

**Comment by logston** [comment]
Thanks @horida! Merged your PR and will cut a release soon.
