### ISSUE TITLE
Unable to install v0.16.4 via pip

### ISSUE THREAD

**Issue by sidmitra** [15five/django-scim2#53]
**Describe the bug**
PYPI describes the latest version as 0.16.4 but unable to install it.

**To Reproduce**
> pip install django-scim2==0.16.4

**Expected behavior**
- 0.16.4 installs correctly 

**Stacktrace**
```
Collecting django-scim2==0.16.4
  Using cached django_scim2-0.16.3-py3-none-any.whl
ERROR: Requested django-scim2==0.16.4 from file:///Users/myuser/Library/Caches/pip/wheels/93/3f/bf/0a26b7ee52fda2c188c8d752d3d7611a6ff375c84b9d0deb01/django_scim2-0.16.3-py3-none-any.whl (from -r requirements.txt (line 64)) has different version in metadata: '0.16.3'
```

**Comment by sidmitra** [comment]
It would seem there's no tagged release for 0.16.4? The last tag i see is 0.16.3 as of today.

**Comment by logston** [comment]
Thanks for finding this issue! Fixed! You'll need to use 0.16.5 though.

**Comment by sidmitra** [comment]
@logston I think there is still an issue. `pyproject.toml` on master still mentions the version as 0.16.3 so it's confusing pip/poetry sometimes.

Or rather when i install it through poetry, it seems to work. But pip complains with the following.

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

myproject 0.1.0 requires django-scim2==0.16.5, but you'll have django-scim2 0.16.3 which is incompatible.
```

This could be a local issue on my end, but regardless my assumption is that the pyproject.toml version should match what is in setup.py etc. Perhaps it just got missed accidentaly.

**Comment by logston** [comment]
Shucks. Can you try `0.16.6` and see if the issue is fixed?

**Comment by sidmitra** [comment]
@logston Thanks for the update. I will take a look later today/tomorrow and leave a comment here.

I've gotten decent mileage out of [bumpversion](https://github.com/peritus/bumpversion) to update version string together in different files. It's worth a look if you're not already using it.

**Comment by logston** [comment]
Thanks for mentioning the issue! And I'll take a look at bumpversion

**Comment by sidmitra** [comment]
@logston Seems to work now. Thanks.
