### ISSUE TITLE
I receive a 501 - Not Implemented, even though the user is successfully created in my DB

### ISSUE THREAD

**Issue by Katert** [15five/django-scim2#60]
Hi, 

I'm implementing your package into my project and I can add users to my database using the scim/v2/Users endpoint. However, each time I send a POST-request, the user does get created in my database but I receive a 501 status-code, instead of a 201 - Created status.
I also get the same status code whenever I try to retrieve a specific user with its ID. 
Can't seem to figure out why this is happening.

This is an example of the message in the request's body:

{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "userName": "abanderas@pos.test",
    "password": "test123",
    "emails": [
        {
            "value": "abanderas@pos.test",
            "type": "work"
        }
    ],
    "externalId": "abanderas",
    "name": {
        "familyName": "Banderas",
        "givenName": "Antonio"
    }
}

**Comment by Katert** [comment]
This can be closed. I solved this by implementing a custom Group which inherits from AbstractSCIMGroupMixin and django.contrib.auth.models.Group. I've declared a ManyToManyField to this custom group called "groups" in my custom User model. After that I override the scim_groups property in my custom User model and set it to return self.groups:


`
class Group(Group, AbstractSCIMGroupMixin):

    def __str__(self):
        return self.scim_display_name


class User(AbstractUser, AbstractSCIMUserMixin):

    email = EmailField(unique=True)
    scim_username = models.CharField(
        _('SCIM Username'),
        max_length=254,
        null=True,
        blank=True,
        default=None,
        unique=True,
        db_index=True,
        help_text=_("A service provider's unique identifier for the user"),
    )
    groups = models.ManyToManyField(Group)

    @property
    def scim_groups(self):
        return self.groups

    USERNAME_FIELD = 'scim_username'

    def __str__(self):
        return self.email
`

I'm receiving the correct responses now.

**Comment by Katert** [comment]
Hi Paul,

I'm reopening this issue because I wanted to ask if the way I solved this is okay. 
There are 2 Group-tables in my DB now, one of which has the SCIM-fields with a pointer ID to the corresponding auth.Group model. 
It all seems to be working like I would expect, but wanted to ask your view on this. 

Thanks in advance.

**Comment by logston** [comment]
Hey @Katert, that certainly is an option. We've seen a number of ways of integrating this library with the existing code bases. The setup you've mentioned might even be better for you down the road given its decoupled nature.
