### ISSUE TITLE
Requests are only approved when a cookie-header is provided

### ISSUE THREAD

**Issue by weskat** [15five/django-scim2#61]
Hi, 

I'm not able to access the SCIM-endpoints while using a Bearer token (OAuth 2) or using Basic Authentication, while all my other endpoints (other than SCIM) do allow this. 
I've figured out that my requests to the SCIM endpoints do succeed when I provide a Cookie-header in my request, with references to the csrf-token and sessionid. If I don't do this, I always get a 401 - Unauthorized, even if I provide a Bearer token or login credentials.

I have included your middleware after the authentication-middleware as instructed in your documentation, but I can't seem to use the SCIM-endpoints without providing a Cookie-header in my request. 
Is this expected behavior or did I configure something wrong?

**This is a portion of my settings.py file:**

`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'api',
    'corsheaders',
    'django_filters',
    'django_scim',
    'oauth2_provider'
]

SCIM_SERVICE_PROVIDER = {
    'NETLOC': 'localhost',
    'AUTHENTICATION_SCHEMES': [
        {
            'type': 'oauth2',
            'name': 'OAuth 2',
            'description': 'Oauth 2 implemented with bearer token',
            'primary': 'true'
        },
        {
            "name": "HTTP Basic",
            "description": "Authentication scheme using the HTTP Basic Standard",
            "type": "httpbasic"
        }
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_scim.middleware.SCIMAuthCheckMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}`

**Comment by behconsci** [comment]
@Katert which cookie header are you talking about? I am having the same issue but can't solve it with the steps you have. 

I am testing with Okta: 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/10358323/163575227-4412b713-e188-4d13-936e-cad96f54779a.png">
