### ISSUE TITLE
Not syncing the group members

### ISSUE THREAD

**Issue by paulorfmmb** [15five/django-scim2#69]
Hi,

When I do the provisioning from my AD the group members are not been saved. I get all the groups and users but the groups have no users in it.

**Comment by logston** [comment]
Thanks for letting us know. Do you have any logging to show what the Group assignment requests are being sent? If you allow for debug logging from the django-scim logger, you should be able to see each request pass through:

https://github.com/15five/django-scim2/blob/8a90e03e0d52f8194c2de722cf5a08ff5a79889c/src/django_scim/middleware.py#L101

**Comment by paulorfmmb** [comment]
Sorry I'm new at this. I'm using you example project, how can I allow the debug log to go through?

**Comment by logston** [comment]
Oh in your settings file, you can add a logger and specify a lower logging level:

https://docs.djangoproject.com/en/4.0/topics/logging/
```
import os

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
```

https://github.com/15five/django-scim2/blob/master/demo/root/settings.py#L204-L209

You can change the handlers in the demo to be console if that helps you debug: 
```
        'scim': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
```

**Comment by paulorfmmb** [comment]
Hi, I solved the issue, there were some improper configuration on my part. Thanks for the help

**Comment by johnboy14** [comment]
> Hi, I solved the issue, there were some improper configuration on my part. Thanks for the help

Can you share what configuration you used?
