### ISSUE TITLE
userName attribute should  be case-insensitive, per the RFC

### ISSUE THREAD

**Issue by mateuszmandera** [15five/django-scim2#76]
See https://datatracker.ietf.org/doc/html/rfc7643#section-4.1.1: (`userName`)

> This attribute is REQUIRED and is **case insensitive**.

Currently this case-insensitive behavior is not implemented and the `filter` lookups are case-sensitive.

**Comment by andersk** [comment]
Currently, the Django `Q` object transpiler is [always case-insensitive](https://github.com/15five/scim2-filter-parser/blob/0011bd2ab6d97278f4da10a834f2314fcd088252/src/scim2_filter_parser/transpilers/django_q_object.py#L215-L219), but the SQL transpiler is [always case-sensitive](https://github.com/15five/scim2-filter-parser/blob/0011bd2ab6d97278f4da10a834f2314fcd088252/src/scim2_filter_parser/transpilers/sql.py#L19-L23).

It looks like it would be simple to make it always case-insensitive, by changing `=` to `ILIKE`, `!=` to `NOT ILIKE`, and `LIKE` to `ILIKE`, with a corresponding adjustment to the [`'LIKE' == op_sql` condition](https://github.com/15five/scim2-filter-parser/blob/0011bd2ab6d97278f4da10a834f2314fcd088252/src/scim2_filter_parser/transpilers/sql.py#L145) and [`matching_op_by_scim_op`](https://github.com/15five/scim2-filter-parser/blob/0011bd2ab6d97278f4da10a834f2314fcd088252/src/scim2_filter_parser/transpilers/sql.py#L32-L34).

I’m not sure if that’s the desired behavior.

**Comment by mateuszmandera** [comment]
`ILIKE` would seem simpler (though possibly still not quite easy if it was to be handled fully correctly, since the transpiler would have to be aware that it should do this only in the case of `userName` but not other attributes :thinking: ) - but given that it's pattern matching rather than equality, I wonder if special characters wouldn't become an issue in some way.

**Comment by logston** [comment]
Nice find @mateuszmandera. This is indeed tricky. It's been a while since I've touched this code. Let me see what I can come up with.

**Comment by logston** [comment]
A patch is up on the scim2-filter-parser repo.
