### ISSUE TITLE
Unauthorized issues

### ISSUE THREAD

**Issue by idolieb26** [15five/django-scim2#77]
I am getting the `unauthorized issues` on `scim` endpoints I know authentication and authorization is not implemented on django-scim. That is why I integrated [Django OAuth Toolkit](https://github.com/evonove/django-oauth-toolkit).
But it didn't work out. I tested demo project, but I am getting the same issue.

**Describe the bug**
Unauthorized: /scim/v2/Users
"GET /scim/v2/Users HTTP/1.1" 401 0

**Expected behavior**
I want to retrieve `/scim` endpoint with Bearer token.

**Comment by logston** [comment]
Hi @idolieb26, can you share the full request payload (including the headers)?

**Comment by idolieb26** [comment]
@logston 

 /scim/v2/Users/?count=1&startIndex=1
 
**_Header_**
{ "Authorization": "Bearer 8b531ddde96531fe0a1ee09a4bbac957bfe895c1" }

**Comment by logston** [comment]
Hmm, are you sure that's causing your request object to appropriately be associated with a user? 

If its not, it could result in 401s:

https://github.com/15five/django-scim2/blob/master/src/django_scim/middleware.py#L52-L56

You might try turning on more logging to get a fuller picture of what's happening. 

Here's an example of how to configure the logging:
https://github.com/15five/django-scim2/blob/master/demo/root/settings.py#L115-L210

You'll need to add a `console` handler though if you don't have FluentBit running.

**Comment by logston** [comment]
Please feel free to reopen if this needs future investigation.
