### ISSUE TITLE
Support SCIM views with custom authentication mechanisms

### ISSUE THREAD

**Issue by PIG208** [15five/django-scim2#78]
[login_requried](https://github.com/15five/django-scim2/blob/d833026aaefaeed23e5a4a765c9d1ca699d94e01/src/django_scim/views.py#L107) was added to `SCIMView.dispatch` in https://github.com/15five/django-scim2/commit/f791a4421ad1b141d2fd72d1fdfdb058df547b5f, marking all requests to the SCIM views required for authentication.

This ties with authentication based on the `request.user` object added by Django's `AuthenticationMiddleware`, therefore requiring us to actually have a `User` object representing an authenticated client.

This is not necessarily the case when there isn't a corresponding `AUTH_USER_MODEL` that can be associated with the SCIM client. `login_required` ensures the presence of `user` which `is_authenticated`, but it does not have anything to do directly with the views themselves.

A current workaround is to create a class preventing to be `AUTH_USER_MODEL`, that implements `is_authenticated`. This breaks type-safety and Django's expectation for `request.user`. But it would be better if django-scim2 actually supports custom authentication methods for the SCIM views.

Additional context can be found [here](https://chat.zulip.org/#narrow/stream/3-backend/topic/.60RemoteZulipServer.60.20not.20as.20.60request.2Euser.60/near/1403307).

**Comment by logston** [comment]
> This is not necessarily the case when there isn't a corresponding AUTH_USER_MODEL that can be associated with the SCIM client. 

Great point. A use case where unauthenticated requests are permitted was not considered when developing this package. Also, a use case where a non-Django (ie. `AUTH_USER_MODEL`) could authenticate to the views was not considered. 

Do you have a suggested implementation? My initial reaction is to abstract away the `.dispatch` middleware and allow for a custom authn middleware before `.dispatch` is processed, as I believe you've suggested.

**Comment by PIG208** [comment]
Thank you! That sounds like a reasonable approach.

**Comment by andersk** [comment]
#82 still only supports predicates that are a function of `AUTH_USER_MODEL` objects (`request.user`). We want to authenticate SCIM views with a bearer token, not with Django’s user system, so that doesn’t help our use case. We need to use a predicate that’s a function of `request`, not a function of `request.user`.

**Comment by logston** [comment]
@andersk, please review https://github.com/15five/django-scim2/pull/84 to ensure it meets your needs.
