### ISSUE TITLE
0.4.{0,1} Python2 is not supported because of using `from urllib.parse import urljoin`

### ISSUE THREAD

**Issue by pymen** [15five/django-scim2#8]
The right way to use

v 0.3.0

`from six.moves.urllib.parse import urljoin`

or 

    try:
        from urllib.parse import urlparse
    except ImportError:
        from urlparse import urlparse

the same with 
try:
    import unittest.mock as mock
except ImportError:
    import mock

**Comment by pablodiazgutierrez** [comment]
Running into this right now. Is there a fork somewhere that does this, or would a PR be welcome?

**Comment by logston** [comment]
PR is welcome.

**Comment by logston** [comment]
Closed with https://github.com/15five/django-scim2/pull/12
