### ISSUE TITLE
Re-creating of users

### ISSUE THREAD

**Issue by SamSchelfhout** [15five/django-scim2#83]
I was wondering if there is a way to handle re-creation of users. 
When a user gets created, removed (set to inactive), and created again, django will throw the exception that the user already exists. I`m not sure what is the safest way to implement that.

Also, is there a way to limit which user (type) can execute the scim api calls?

And thanks for the library, it saves me tons of work!

**Comment by logston** [comment]
Hey @SamSchelfhout, the pattern that I often see used is, like you said, to soft delete a user (mark them as inactive) and then unmark them when they are recreated. The [SCIM Adapters](https://github.com/15five/django-scim2/blob/d833026aaefaeed23e5a4a765c9d1ca699d94e01/src/django_scim/adapters.py#L113-L114) are [designed to be](https://github.com/15five/django-scim2/blob/master/src/django_scim/views.py#L325-L327) [overridden](https://github.com/15five/django-scim2/blob/d833026aaefaeed23e5a4a765c9d1ca699d94e01/demo/root/settings.py#L220-L222) if you need custom behavior; for example during POSTs or DELETEs.

> Also, is there a way to limit which user (type) can execute the scim api calls?

This could be done in the same calls as mentioned above. But there's also [a PR](https://github.com/15five/django-scim2/pull/82) up that would allow customizable authn/z operations. Extra limitations could be added in the customized auth module..

Thanks for the positive vibes 👍 .

**Comment by SamSchelfhout** [comment]
Thanks @logston, I got it to work.

I had already implemented my own version of the SCIMAuthCheckMiddleware and the process_request function. I`ll change my code once the pull request is merged and available.

Thanks!
