### ISSUE TITLE
Support SCIM 1.1 Implementations 

### ISSUE THREAD

**Issue by omidraha** [15five/django-scim2#88]
Support SCIM 1.1 Implementations

http://www.simplecloud.info/#Specification

Many Service providers currently used SCIM 1.1.

This library may be useful for development to support version 1.1.

https://github.com/concordusapps/python-scim

**Comment by logston** [comment]
Hi @omidraha, thanks for the suggestion. But given the evolving standard and the move of most of the larger service providers to SCIM 2+ (or SCIM 2 compatible APIs), we explicitly decided not to support SCIM 1.1 in this package. Doing so allows us to keep a cleaner, safer, and more maintainable package.
