### ISSUE TITLE
GitHub Sponsor

### ISSUE THREAD

**Issue by mikeumus** [15five/django-scim2#93]
Would love to sponsor this project. 💖😊

**Comment by mikeumus** [comment]
@logston what do you think? 😀

**Comment by logston** [comment]
Hi @mikeumus, this is very kind of you. But this project is owned by 15Five, my previous employer, and so I'm not sure how they would want to proceed. Perhaps @caleb15 could chime in with whether or not 15Five would like to setup sponsorship?

**Comment by caleb15** [comment]
I don't see any issue with sponsorship money going to @logston as he is the primary maintainer. 

When I click on "Set up sponsor button" it creates a PR draft with the file `FUNDING.yml` and the following contents:

```
# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
```

I'm not sure which one you prefer to use so if you want sponsorship please create a PR like the above with your desired links.

**Comment by logston** [comment]
Thanks @caleb15. Perhaps we could get 15Five's legal or people team to weigh in on something like this too? Just want to make sure we've done our due diligence.

**Comment by caleb15** [comment]
We could do that, but to be honest I'm not sure it's worth it unless the sponsorship amount is significant enough. @mikeumus how much are we talking about here, 50+?

**Comment by logston** [comment]
Sorry @caleb15 but I have to insist. Given the legal repercussions, we should really have something like this approved by 15Five's directors or above. Many thanks for the effort though.

**Comment by Almenon** [comment]
What I meant by my last comment was that it's not worth setting up sponsorship unless the contribution is a above a certain level where the gains would be worth bothering legal over.

**Comment by caleb15** [comment]
What I meant by my last comment was that it's not worth setting up
sponsorship unless the contribution is a above a certain level where the
gains would be worth bothering legal over.

**Comment by caleb15** [comment]
Hmm. No response from mikeumus, but I suppose even if the amount they donate is small other people might want to donate too in the future, so it could be worth asking legal over. 

I'm leaving 15Five next Tuesday, so @jamesjsanders I'm wondering if you can ask legal counsel about this? To summarize, we are wondering whether sponsorship could be setup for this open-source project, directing the funds to Paul as he is the primary maintainer.
