### ISSUE TITLE
ModuleNotFoundError: No module named 'django_scim'

### ISSUE THREAD

**Issue by mikeumus** [15five/django-scim2#94]
**Describe the bug**
`ModuleNotFoundError: No module named 'django_scim'`

**To Reproduce**
Add `django_scim` Django (cookiecibtter. 

**Expected behavior**
`django_scim2` module to be found and docker to complete spin-up. 

**Stacktrace**
<img width="1006" alt="Screenshot 2022-10-28 at 2 47 56 AM" src="https://user-images.githubusercontent.com/57934/198558460-d676e7b1-64f7-412c-9234-b13ae055bd1d.png">

**Additional context**
<img width="908" alt="Screenshot 2022-10-28 at 2 56 07 AM" src="https://user-images.githubusercontent.com/57934/198560374-ca897fef-03ea-4cb3-8d79-67946739a26f.png">

<img width="772" alt="Screenshot 2022-10-28 at 2 59 45 AM" src="https://user-images.githubusercontent.com/57934/198560841-48c16b15-754f-42ff-a151-534f077acdcc.png">

```
> $ pip list -V | grep django-scim2                                                                                                 [±main ●]
django-scim2             0.17.3
```

Addded `django_scim2` to `requirements.txt`
```
django-scim2==0.17.3  # https://github.com/15five/django-scim2
```

**Comment by logston** [comment]
Hi @mikeumus, thanks for the issue. If I'm not mistaken, this looks like its triggered by an attempt to build the docs. You'll need to be in the docs directory to correctly build the docs. There path manipulation that happens at the top of `conf.py` in that folder: https://github.com/15five/django-scim2/blob/20ac22b/docs/conf.py#L19-L27

**Comment by mikeumus** [comment]
After adding `django-scim2==0.17.3` to `requirements.txt` and deleting the images+containers+volumes and `docker-compose up`'ing once more, it worked! Thanks @logston 🙇🏻‍♂️
