### ISSUE TITLE
Decouple User model from SCIM attributes?

### ISSUE THREAD

**Issue by William-Wildridge** [15five/django-scim2#96]
**Is your feature request related to a problem? Please describe.**
I'm delighted to find django-scim2 and am excited to use it to connect to AzureAD. 

I am not sure how to fix this error: AttributeError:  'User' object has no attribute 'scim_id'.

I don't think I can copy the User implementation in the demo: 

`class User(AbstractSCIMUser, TimeStampedModel, AbstractBaseUser):`

as [django documentation warns against implementing a custom user model mid project](https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project) and I haven't implemented a custom user model from the beginning.

**Describe the solution you'd like**
I'd like to implement a 'profile style' model to store my scim related data in, like so:

```
class UserScim(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = 'user_scim')
	scim_id = models.CharField(
		_('SCIM ID'),
		max_length=254,
		null=True,
		blank=True,
		default=None,
		unique=True,
		help_text=_('A unique identifier for a SCIM resource as defined by the service provider.'),
	)
        scim_external_id = models.CharField(
                _('SCIM External ID'),
                max_length=254,
                null=True,
                blank=True,
                default=None,
                db_index=True,
                help_text=_('A string that is an identifier for the resource as defined by the provisioning client.'),
        )
	def __str__(self):
		return self.user.username + ' ' + str(self.scim_id)
```

Would this decoupling work? What would I need to update elsewhere?

Thank you very much.

**Comment by logston** [comment]
Hi @William-Wildridge, thanks for the question. I'm currently very strapped for time so I apologize but I don't have the bandwith to answer this in detail. 

In summary, yes that decoupling would work. You'd need to update the [adapters ](https://django-scim2.readthedocs.io/en/latest/adapters.html)to take action on the User model rather than the UserScim model. 

If you have more specific questions, I might be able to address those more completely.

**Comment by William-Wildridge** [comment]
Hi @logston, 

Thank you so much for the reply and pointing me in the right direction.

Yes referring to the user_scim model in a custom adapters.py file works for this use case.

I've got this working now for several of the endpoints : )

All the best,
William

**Comment by devendra-rgb** [comment]
Hi @William-Wildridge @logston  I am also trying to decouple the User model like how you created but even I am modifying the adapters it is pointing to my main Django Model could you please help me  on this how you did : )
